### PR TITLE
Proper indent when lists are used in block

### PR DESCRIPTION
**Pull request by skwde**
Only the first list item was properly indented. In case of the RHEL7 default config the indent was like

```config
#
# Ansible managed
#
Host *
  ForwardX11Trusted yes
  GSSAPIAuthentication yes
  SendEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
SendEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
SendEnv LC_IDENTIFICATION LC_ALL LANGUAGE
SendEnv XMODIFIERS
```

this is now fixed. I.e. the default results in 

```config
#
# Ansible managed
#
# system_role:ssh

Host *
  ForwardX11Trusted yes
  GSSAPIAuthentication yes
  SendEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
  SendEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
  SendEnv LC_IDENTIFICATION LC_ALL LANGUAGE
  SendEnv XMODIFIERS
```

### CODE REVIEW

**Comment by spetrosi** [comment]
[citest]

**Comment by richm** [comment]
you'll also need to fix the scripts in the .dev-tools directory - the templates/ssh_config.j2 is generated from the scripts in the .dev-tools directory

**Comment by skwde** [comment]
@richm I just did the changes also in `.dev-tools/10_top.j2`.

Can I also start the test?

[citest]

**Comment by richm** [comment]
@skwde how are you testing this?

**Comment by richm** [comment]
> @skwde how are you testing this?

This is what I've tried:
```
tests_global_config.yml:
...
        ssh:
...
          Host:
            Condition: example
            Hostname: example.com
            User: somebody
            SendEnv: [LANG, LC_CTYPE, LC_NUMERIC, LC_TIME, LC_COLLATE, LC_MONETARY, LC_MESSAGES, LC_PAPER, LC_NAME, LC_ADDRESS, LC_TELEPHONE, LC_MEASUREMENT, LC_IDENTIFICATION, LC_ALL, LANGUAGE, XMODIFIERS]
```
which has the following output:
```
Host example
  Hostname example.com
  SendEnv LANG
  SendEnv LC_CTYPE
...
  SendEnv XMODIFIERS
  User somebody
```
which looks correct - but doesn't match yours:
```
  SendEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
  SendEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
  SendEnv LC_IDENTIFICATION LC_ALL LANGUAGE
  SendEnv XMODIFIERS
```
so I'm not sure if my test is exercising the code that causes the error, or how to reproduce your output

**Comment by richm** [comment]
ok - figured it out
```
            SendEnv:
              - LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
              - LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION
              - LC_ALL LANGUAGE XMODIFIERS
```
produces the correct output
so lgtm - @Jakuje ?

**Review by richm — APPROVED** [review]

**Comment by skwde** [comment]
@richm, Indeeded, you can even do it simpler, just run the default RHEL7:

```yml
- name: Test
  hosts: rhel7
  gather_facts: true
  roles:
    - role: fedora.linux-system-roles.ssh
  become: true
```

**Comment by richm** [comment]
I submitted https://github.com/skwde/ssh/pull/1 - I think since spacing and indentation are significant, we should have a test for that

**Comment by richm** [comment]
[citest]

**Pull request merged**
